name: CI Frontend y Backend - TecnoRepuestos

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:
    name: CI Backend (Node.js + Tests)
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias Backend
        run: npm install
        working-directory: backend

      - name: Ejecutar pruebas Backend
        run: npm test
        working-directory: backend

  frontend:
    name: CI Frontend (Build)
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias Frontend
        run: npm install
        working-directory: frontend

      - name: Construir Frontend
        run: npm run build
        working-directory: frontend
